FROM node:18-alpine

RUN apk add --no-cache openssl

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npx prisma generate

EXPOSE 5001

CMD ["sh", "-c", "npx prisma db push && node prisma/seed.js && npm run dev"]

